Create Table COURSE_INFO (COURSE_NO NUMERIC(8,0),  COST NUMERIC(5,0))

Create Table INSTRUCTOR_INFO (NSTRUCTOR_ID NUMERIC(8,0),  INSTRUCTOR_FIRST_NAME VARCHAR(15),INSTRUCTOR_LAST_NAME VARCHAR(15))

Create Table ZIPCODE_INFO (ZIP_CODE VARCHAR(5),  CITY VARCHAR(10));

Create Table STUDENT_INFO (STUDENT_ID NUMERIC(8,0),  STUDENT_FIRST_NAME VARCHAR(15),STUDENT_LAST_NAME VARCHAR(15));

Create Table SECTION_INFO (SECTION_ID NUMERIC(8,0),  COURSE_NO NUMERIC(8,0),SECTION_NO NUMERIC(5), INSTRUCTOR_ID NUMERIC(8,0))

Create Table ENROLLMENT_INFO (STUDENT_ID NUMERIC(8,0),  SECTION_ID NUMERIC(8,0))

Create Table GRADE_INFO (STUDENT_ID NUMERIC(8,0),  SECTION_ID NUMERIC(8,0),GRADE_TYPE_CODE CHAR(2),GRADE_CODE_OCCURANCE NUMERIC(5));